/**
 * YouTube 쿠키 추출 도구
 * 브라우저 콘솔에서 실행하여 YouTube 쿠키를 추출합니다.
 *
 * 사용법:
 * 1. YouTube에 로그인
 * 2. 시크릿/개인 브라우징 모드에서 YouTube 로그인
 * 3. https://www.youtube.com/robots.txt 방문 (중요!)
 * 4. F12 -> 콘솔에서 이 스크립트 실행
 * 5. 결과를 복사하여 Lambda 환경변수 또는 API 요청에 사용
 */

function extractYouTubeCookies() {
    console.log('🍪 YouTube 쿠키 추출 시작...');

    // YouTube 도메인의 모든 쿠키 가져오기
    const cookies = document.cookie.split(';').map(cookie => {
        const [name, value] = cookie.trim().split('=');
        return `youtube.com\tTRUE\t/\tFALSE\t0\t${name}\t${value || ''}`;
    }).join('\n');

    // Netscape 형식으로 변환
    const netscapeCookies = `# Netscape HTTP Cookie File
# Generated by YouTube Cookie Extractor
# This file contains the HTTP cookies for youtube.com

${cookies}`;

    console.log('✅ 쿠키 추출 완료!');
    console.log('\n📋 아래 내용을 복사하세요:');
    console.log('=====================================');
    console.log(netscapeCookies);
    console.log('=====================================');

    // 클립보드에 복사 시도
    try {
        navigator.clipboard.writeText(netscapeCookies);
        console.log('✅ 클립보드에 복사되었습니다!');
    } catch (error) {
        console.log('⚠️  클립보드 복사 실패. 수동으로 복사해주세요.');
    }

    return netscapeCookies;
}

function extractSimpleCookies() {
    console.log('🍪 간단한 쿠키 추출...');

    const cookies = document.cookie;
    console.log('📋 쿠키 문자열:');
    console.log(cookies);

    try {
        navigator.clipboard.writeText(cookies);
        console.log('✅ 클립보드에 복사되었습니다!');
    } catch (error) {
        console.log('⚠️  클립보드 복사 실패. 수동으로 복사해주세요.');
    }

    return cookies;
}

// 자동 실행
console.log(`
🚀 YouTube 쿠키 추출 도구
======================

방법 1: 전체 쿠키 추출 (권장)
→ extractYouTubeCookies()

방법 2: 간단한 쿠키 추출
→ extractSimpleCookies()

⚠️  중요 사항:
1. 시크릿/개인 브라우징 모드 사용
2. https://www.youtube.com/robots.txt 먼저 방문
3. 추출 후 즉시 시크릿 창 닫기
4. 계정 보안을 위해 주기적으로 새 쿠키 생성

현재 페이지: ${window.location.href}
`);

// robots.txt 확인
if (window.location.href.includes('robots.txt')) {
    console.log('✅ robots.txt 페이지에서 실행 중 - 최적의 조건입니다!');
    console.log('📝 extractYouTubeCookies() 를 실행하세요');
} else {
    console.log('⚠️  권장: https://www.youtube.com/robots.txt 에서 실행하세요');
}